### DISCUSSION TITLE
redirection to localhost

### DISCUSSION THREAD

**Discussion by gkrwns7566** [aminalaee/sqladmin#475] [Q&A] [answered]
the admin application is running on a docker-compose environment in ec2 with nginx.
![image](https://user-images.githubusercontent.com/122417974/233258626-d7017717-e578-4eb4-b238-e13cd590e574.png)

![image](https://user-images.githubusercontent.com/122417974/233258255-6faf0e04-999b-4cb4-a4a9-1d776239c125.png)

the project works perfectly on local environment, but doesn't work properly in remote as shown above.

I've went through configurations of load balancer, nginx, sqladmin settings, but couldn't find the reason of such redirection. 

Below is the admin setting
`admin = Admin(base_url='/th/admin', app=app, engine=engine, authentication_backend=authentication_backend)`

What could be the reason for these actions??

**Comment by aminalaee** [comment]
Hi,
I think it's probably not related to SQLAdmin but I'll try to help if I can.

> he project works perfectly on local environment, but doesn't work properly in remote as shown above.

Are you using docker-compose in your local env too?

What does your docker-compose file look like?

**Reply by gkrwns7566** [reply]
```
version: "3.7"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload"
    volumes:
      - ./app:/code/app
    env_file:
      - env/dev.env

```
here's my docker-compose.yml file that i used in my local environment
